
#######

name: Rotate AWS Keys

on:
   push:
  # workflow_dispatch: {}
  # schedule:
  #   - cron: "0 8 * * 0"  # Every Sunday at 08:00 UTC

jobs:
  rotate_keys:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      actions: read
      secrets: write

    env:
      AWS_USERNAME: terraform
      ROTATION_DAYS: "60"
      GITHUB_REPO_FULLNAME: ${{ github.repository }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install boto3 requests pynacl

      - name: Rotate AWS keys
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python ./rotate_aws_keys_github.py \
            "$AWS_USERNAME" \
            "$GITHUB_TOKEN" \
            "$GITHUB_REPO_FULLNAME" \
            "$ROTATION_DAYS"
